"""empty message

Revision ID: 170807cd11e7
Revises: 5879fb55aedb
Create Date: 2021-07-18 10:55:01.408330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170807cd11e7'
down_revision = '5879fb55aedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('town_pollutant',
    sa.Column('town_id', sa.String(length=100), nullable=False),
    sa.Column('pollutant_id', sa.String(length=100), nullable=False),
    sa.Column('pollutant_level', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['pollutant_id'], ['pollutant.id'], ),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], ),
    sa.PrimaryKeyConstraint('town_id', 'pollutant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('town_pollutant')
    # ### end Alembic commands ###
