"""empty message

Revision ID: 27180738d732
Revises: 170807cd11e7
Create Date: 2021-07-24 17:04:54.609149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27180738d732'
down_revision = '170807cd11e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255)))
    op.add_column('user', sa.Column('password', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
