"""empty message

Revision ID: 5879fb55aedb
Revises: 
Create Date: 2021-07-16 16:18:26.272426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5879fb55aedb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parish',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollutant',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('safe_level', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('town',
    sa.Column('id', sa.String(length=100), nullable=False, unique=True),
    sa.Column('parish_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parish.id'], ),
    sa.PrimaryKeyConstraint('id', 'parish_id')
    )
    op.create_table('planning_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('town_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_application_area_pollutant',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('pollutant_id', sa.String(length=100), nullable=False),
    sa.Column('pollutant_level', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['planning_application.id'], ),
    sa.ForeignKeyConstraint(['pollutant_id'], ['pollutant.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'pollutant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_application_area_pollutant')
    op.drop_table('planning_application')
    op.drop_table('town')
    op.drop_table('user')
    op.drop_table('pollutant')
    op.drop_table('parish')
    # ### end Alembic commands ###
