"""empty message

Revision ID: 7da8503632df
Revises: 80cf4dd1529d
Create Date: 2021-08-16 22:03:33.911791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da8503632df'
down_revision = '80cf4dd1529d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targeted_pollutant', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_targeted_pollutant_tree_id_tree'), 'tree', ['tree_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_targeted_pollutant_targeted_pollutant_id_pollutant'), 'pollutant', ['targeted_pollutant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_targeted_pollutant_report_id_report'), 'report', ['report_id'], ['id'])

    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_to_maturity', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_column('age_to_maturity')

    with op.batch_alter_table('targeted_pollutant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_targeted_pollutant_report_id_report'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_targeted_pollutant_targeted_pollutant_id_pollutant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_targeted_pollutant_tree_id_tree'), type_='foreignkey')

    # ### end Alembic commands ###
