"""empty message

Revision ID: 8a54cd45347c
Revises: 3ccc529aa1cb
Create Date: 2021-07-28 12:18:21.800405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54cd45347c'
down_revision = '3ccc529aa1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_type',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tree_type'))
    )
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tree_type_id_tree_type'), 'tree_type', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tree_type_id_tree_type'), type_='foreignkey')
        batch_op.drop_column('type_id')
    op.drop_table('tree_type')
    # ### end Alembic commands ###
