"""add tree and tree efficacy models

Revision ID: bf03df5ba949
Revises: f8c0611369cc
Create Date: 2021-07-27 17:47:08.744920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf03df5ba949'
down_revision = 'f8c0611369cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('maturity_size', sa.Numeric(precision=2), nullable=False),
    sa.Column('space_required', sa.Numeric(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_efficacy',
    sa.Column('tree_id', sa.String(length=100), nullable=False),
    sa.Column('pollutant_id', sa.String(length=100), nullable=False),
    sa.Column('effectiveness', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['pollutant_id'], ['pollutant.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('tree_id', 'pollutant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree_efficacy')
    op.drop_table('tree')
    # ### end Alembic commands ###
