"""empty message

Revision ID: f8c0611369cc
Revises: 170807cd11e7
Create Date: 2021-07-23 16:04:40.660203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c0611369cc'
down_revision = '27180738d732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_application', sa.Column('square_footage', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_application', 'square_footage')
    # ### end Alembic commands ###
